max_width = 100
error_on_line_overflow = false
closure_block_indent_threshold = 0
chain_indent = "Block"
format_strings = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
